#!/bin/sh
#
# order - Dump the build order, optionally for a bundle.
#

. "$(dirname $0)/../lib/common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ]

OPTIONS:

  --bundle B   Include only bundle B in the output
  --file F     Take input from file F

EOF
}

BUNDLE=

[ -t 0 ] \
    && FILE=unibuild-order \
    || FILE=""

while [ "$1" ]
do
    case "$1" in

	--bundle)
	    BUNDLE="$2"
	    shift
	    shift
	    ;;

	--file)
	    FILE="$2"
	    shift
	    shift
	    ;;

	--help)
	    help
	    exit 0
	    ;;

	--*)
	    die "Unknown option '$1'"
	    ;;

	*)
	    die "Unknown argument '$1'"
	    ;;
    esac
done

cat ${FILE} | build_order "${BUNDLE}"

exit 0
