FROM debian:10

# Install pre-requisites for building packages
RUN apt-get update -y && \
    apt-get install -y sudo apt-utils curl devscripts emacs-nox gnupg htop pylint rsync screen tree vim

# Copy unibuild source
COPY . /usr/share/unibuild/

# Install unibuild
WORKDIR /usr/share/unibuild
RUN make RELEASE=1

# Shared volume for code to build
VOLUME /app
WORKDIR /app
