version: '3.9'

###
# Some repeated defaults:
###
x-volumes:
  &default-volumes
  - .:/app

###
# Services
# Note: build: instructions are better moved to docker-bake.hcl
###
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el7
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el8
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el9
    volumes: *default-volumes
  d11_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:e88f10703603bdb4c2219f4927ec25f8e7e46e8ddfabe262cb0054b8a6b9e461
    volumes: *default-volumes
  d11_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:dff28ee104b9649128c2c03059df8db6b53ea46b741f449434497b02c661596a
    volumes: *default-volumes
  d11_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:8f2d69ee658b169f1dc35f1c036ceb562145b33d8753f2a5cbcebe61450ab080
    volumes: *default-volumes
  d11_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:1a053804e8be1271387d4b16882327b7b067faa521d4bc913bf88dc4121a3455
    volumes: *default-volumes
  d12_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:0b1d3f57853f16d7251ac328d670c6af209578550c3b4b9ec48c24ffc7c8c740
    volumes: *default-volumes
  d12_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:64f3e174878cc86ab07899a3b01551409604a4d410b78d2b4a662f691faf8503
    volumes: *default-volumes
  d12_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:dff9d9cd902df20c4e91a9c357a6d50414f95921f32eea1960f27fdb138dae52
    volumes: *default-volumes
  d12_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:e3a0b4e50cbb49a05f422839827d815fa8f1b85317cdf9e2864e6b249786c21a
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:cb587c42b7d12575c8510c1d09beaa0d52c14523316737f7714b90a7870e000e
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:fb7ae46f697b2201d613077f017435f075fb2309e833cb20c65a862131899283
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:21ca5a06cd71a946ff3c5e0965c4164fa45e8bb0831a0d21c72b568aeffa77ff
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:8ea06ccff6bd61549531385060cc20b82ac02866f859261cbf74e88de0a1d198
    volumes: *default-volumes
  u22_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:1d9d0cfcef556aa986a771afc2be34989250859a09ecfdbabd3c25bbc8def34e
    volumes: *default-volumes
  u22_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:8e0ea73269ed7748246caae5b6ec2bf04599070164935c5566497cb5a0ba3cb4
    volumes: *default-volumes
  u22_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:561f7d1fa5f633bb856502af26dfad972079841e48750c6caaf4448a3deb56fa
    volumes: *default-volumes
  u22_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:07d866df2906cc2a18d64d8b5b68ac182e10804034ef7ac540145c023da15092
    volumes: *default-volumes
  u24_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:98d77e7dec8c6a96065592ac24fea2d4dcf8852910034fbccaa4fcc1dbb5dc10
    volumes: *default-volumes
  u24_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:002b744fbee0c3fdf646364e7e7f05e86b96969ee8b4d8841b571a528596b351
    volumes: *default-volumes
  u24_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:98a9787c78bfcc57105cfe74544a9c9e109e2194e83b4e68baca253598ca61b0
    volumes: *default-volumes
  u24_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:fd95fd2006814a9ab6fd7d8e677b2c25243068441b9b943bdc470298598f4316
    volumes: *default-volumes
