FROM debian:11.11 AS unibuild-image

# Install pre-requisites for building packages
RUN ./docker-envs/configure-debian

# Configure APT to regularly update its package lists and mirrors.
RUN echo 'APT::Periodic::Update-Package-Lists "1";' > /etc/apt/apt.conf.d/10periodic

# Copy unibuild source
COPY . /usr/share/unibuild/

# Install unibuild
WORKDIR /usr/share/unibuild
RUN make RELEASE=1
RUN /usr/share/unibuild/libexec/prep/prep

# Shared volume for code to build
VOLUME /app
WORKDIR /app
