FROM almalinux:9-minimal

#Install pre-requisites
#Install utils like tree useful for debugging
#Enable powertools since contains common dependencies
RUN microdnf install -y dnf \
    && dnf update -y \
    && dnf install -y rpm rpm-build rpmdevtools m4 make sudo dnf-plugins-core epel-release tree 

#Copy unibuild source
COPY . /usr/share/unibuild/

#Install unibuild
WORKDIR /usr/share/unibuild
RUN make

#Shared volume for code to build
VOLUME /app
WORKDIR /app
