version: '3.9'

###
# Some repeated defaults:
###
x-volumes:
  &default-volumes
  - .:/app

###
# Services
# Note: build: instructions are better moved to docker-bake.hcl
###
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el7
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el8
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el9
    volumes: *default-volumes
  d11_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:b9269f914fadbde9f2fc915d077c668fa92f372c19563cbfb3c486a5e1405bbc
    volumes: *default-volumes
  d11_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:dff28ee104b9649128c2c03059df8db6b53ea46b741f449434497b02c661596a
    volumes: *default-volumes
  d11_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:b195b233b3ce97f49a9a261ef4c1084439a69d38e2b38b982f81d1bfb0f8e6cb
    volumes: *default-volumes
  d11_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:95ff473a1d3faaa3e4cc29869f44e5cedc87463f4b5953aa40b09a095309cfcf
    volumes: *default-volumes
  d12_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:3d4d305254cb30f825359d3f95eb517a81be95c88e2864c98ae857fc8da6ea12
    volumes: *default-volumes
  d12_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:64f3e174878cc86ab07899a3b01551409604a4d410b78d2b4a662f691faf8503
    volumes: *default-volumes
  d12_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:61bf66a9fc0a61b15ff7d4928f1386cee3acab1bd7ba98c0fb6491b57b0d69a4
    volumes: *default-volumes
  d12_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:6aced6ec74467279f1d4fa6c6edb5b94fe81e240f1cc7fb9befd52e3a1ee2b03
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:ef92eada79085b091ad39f17d09d5508ec43cd6593157fbf49155e3f42db6528
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:fb7ae46f697b2201d613077f017435f075fb2309e833cb20c65a862131899283
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:3e907906f7288005ad07f68267aab3f3561e4ff28409f77cc23d1a9708e255ef
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:af2eb8af3fb93dc1e91e979d9074eb013cd81d7841d682ad6a4c06255e5e1f11
    volumes: *default-volumes
  u22_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:8b6498dc22de69f18f9c12cb352143c9dd47fe9eb9b2f87ff735d8c1bc88b606
    volumes: *default-volumes
  u22_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:8e0ea73269ed7748246caae5b6ec2bf04599070164935c5566497cb5a0ba3cb4
    volumes: *default-volumes
  u22_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:8f9588990f714a59409b29b17ee750bb40149c91d950714cfe3207deaad26d30
    volumes: *default-volumes
  u22_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:97cc15d3a1e20c6ab95b23eeeebe69d0f1d601d915094f2e2e907dea613b1a58
    volumes: *default-volumes
  u24_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:576d17d92d1838797ec13c423257c13e79521cf2d00ee6cc036b6ca8472460ce
    volumes: *default-volumes
  u24_arm64:
    platform: "linux/arm64/v8"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:002b744fbee0c3fdf646364e7e7f05e86b96969ee8b4d8841b571a528596b351
    volumes: *default-volumes
  u24_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:9e558737afaf4a5f4790ec8138a90dbb30da283803cb86289d30edd98048391c
    volumes: *default-volumes
  u24_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:2f8112e325db41c139ed5dbae75f4c80ec06bf2a3ebd22a292e10dddb8fc6be9
    volumes: *default-volumes
