FROM almalinux:latest

#Install pre-requisites
RUN dnf update -y && \
    dnf install -y rpm-build m4 make redhat-lsb-core sudo 

#Copy unibuild source
COPY . /usr/share/unibuild/

#Install unibuild
WORKDIR /usr/share/unibuild
RUN make


#Shared volume for code to build
VOLUME /app
WORKDIR /app