# debian:10.11 is the last one tu support ppc64el as platform
FROM debian:10.11 AS unibuild-image

# Install pre-requisites for building packages
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y sudo apt-utils curl devscripts emacs-nox gnupg htop m4 pylint rsync screen tree vim

# Copy unibuild source
COPY . /usr/share/unibuild/

# Install unibuild
WORKDIR /usr/share/unibuild
RUN make RELEASE=1

# Shared volume for code to build
VOLUME /app
WORKDIR /app
