FROM almalinux:10-minimal AS unibuild-image

#Install pre-requisites
#Install utils like tree useful for debugging
#Enable powertools since contains common dependencies
RUN microdnf install -y dnf rpm rpm-build rpmdevtools m4 make sudo dnf-plugins-core epel-release tree \
    && dnf config-manager --enable crb \
    && dnf update -y


#Copy unibuild source
COPY . /usr/share/unibuild/

#Install unibuild
WORKDIR /usr/share/unibuild
RUN make RELEASE=1
RUN /usr/share/unibuild/libexec/prep/prep

#Shared volume for code to build
VOLUME /app
WORKDIR /app
