#!/bin/sh -e
#
# build - Do the default build.
#

. "$(dirname $0)/../common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ]

OPTIONS:

  --start P  Start with package P

EOF
}

START=

while [ "$1" ]
do
    case "$1" in

	--start)
	    START="--start $2"
	    shift
	    shift
	    ;;

	--help)
	    help
	    exit 0
	    ;;

	--*)
	    die "Unknown option '$1'"
	    ;;

	*)
	    break
	    ;;
    esac
done



# Don't quote START; it has multiple words.
$(dirname $0)/make ${START} clean build install

REPO=unibuild-repo
mkdir -p "${REPO}"
exec $(dirname $0)/gather "${REPO}"
