#!/bin/sh -e
#
# build - Do the default build.
#

help()
{
    cat <<EOF
Usage: ${WHOAMI}

This command takes no additional arguments.
EOF
}

if [ $# -ne 0 ]
then
    help
    die
fi


$(dirname $0)/make clean build install

REPO=unibuild-repo
mkdir -p "${REPO}"
exec $(dirname $0)/gather "${REPO}"
