#!/bin/sh -e
#
# m4 - Process a file using m4 with Unibuild's macros available.
#

. "${UNIBUILD}/common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ] [ M4-ARGUMENTS ]

Options:
    --prefix p    Prefix all macros with p
EOF
}

PREFIX=""

while echo "$1" | egrep -q -e '^--'
do
    OPTION=$1
    shift

    case "${OPTION}" in

	--help|-h)
	    help
	    exit 0
	    ;;

	--prefix)
	    PREFIX="$1"
	    shift
	    ;;

	--*)
	    die "Unknown option ${OPTION}.  Use --help for help."
	    ;;
    esac
done


echo unibuild_m4 --prefix "${PREFIX}" "$@"
unibuild_m4 --prefix "${PREFIX}" "$@"
