#!/bin/sh -e
#
# macros - Dump the OS information macros for this system.
#

. "${UNIBUILD}/common"

help()
{
    cat <<EOF
Usage: ${WHOAMI}

This command takes no additional arguments.
EOF
}

if [ $# -ne 0 ]
then
    help
    die
fi


set \
    | egrep -e '^OSINFO_[^=]{1,}=' \
    | sed -e 's/^OSINFO_//g' \
    | tr -d "'" \
    | sort \
    | (
    while read LINE
    do
	printf "%-12s %s\n" \
	       $(echo "${LINE}" | awk -F= '{ print $1 }') \
	       $(echo "${LINE}" | awk -F= '{ print $2 }')
    done
    )

exit 0
