#!/bin/sh -e
#
# macros - Dump the OS information macros for this system.
#

. "${UNIBUILD}/common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ MACRO-NAME ]
EOF
}


MACRO=
case $# in
    0)
	true
	;;
    1)
	MACRO=$(echo "$1" | tr 'a-z' 'A-Z')
	;;
    *)
	help
	die
	;;
esac


macros()
{
    set \
    | egrep -e '^OSINFO_[^=]{1,}=' \
    | sed -e 's/^OSINFO_//g' \
    | tr -d "'"
}


# Easy case: One macro.
if [ "${MACRO}" ]
then
    macros | awk -F= -v MACRO=${MACRO} '$1 == MACRO { print $2; exit 0 } END { exit 1 }'
    exit $?
fi

# Print all macros, formatted nicely for humans.
macros \
    | sort \
    | (
    while read LINE
    do
	printf "%-12s %s\n" \
	       $(echo "${LINE}" | awk -F= '{ print $1 }') \
	       $(echo "${LINE}" | awk -F= '{ print $2 }')
    done
    )

exit 0
