#!/bin/sh
#
# order - Dump the build order, optionally for a bundle.
#

. "${UNIBUILD}/common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ]

OPTIONS:

  --buildable  Include only packages that will build on this platform
  --bundle B   Include only bundle B, 'none' for packages in no bundle
  --file F     Take input from file F

EOF
}

BUNDLE=
BUILDABLE_FILTER=cat
[ -t 0 ] \
    && FILE=unibuild-order \
    || FILE=""

while [ "$1" ]
do
    case "$1" in

	--bundle)
	    BUNDLE="$2"
	    shift
	    shift
	    ;;

	--file)
	    FILE="$2"
	    shift
	    shift
	    ;;

	--buildable)
	    BUILDABLE_FILTER=buildable_filter
	    shift
	    ;;

	--help)
	    help
	    exit 0
	    ;;

	--*)
	    die "Unknown option '$1'"
	    ;;

	*)
	    die "Unknown argument '$1'"
	    ;;
    esac
done

buildable_filter()
{
    DIR=$(dirname "${FILE}")
    while read LINE
    do
	if find "${DIR}/${LINE}" -type d \
		| fgrep -v '/unibuild-work/' \
		| egrep -q -e "/unibuild-packaging/${OSINFO_PACKAGING}\$"
	then
	    echo "${LINE}"
	fi
    done
}

cat ${FILE} | build_order "${BUNDLE}" | $BUILDABLE_FILTER

exit 0
