#!/bin/sh
#
# xyzzy - A do-nothing command.

. "${UNIBUILD}/common"

case "$1" in
    --help)
	printf "\nNothing helpful happens.\n\n"
	;;

    --*)
	printf "\nNothing optional happens.\n\n"
	;;
    
    *)
	printf "\nNothing happens.\n\n"
	;;
esac

exit 0
