#!/bin/sh -e
#
# xyzzy - A do-nothing command.
#

. "${UNIBUILD}/common"

MESSAGE=

case "$1" in
    --help)
	MESSAGE="Nothing helpful happens."
	shift
	;;

    --*)
	MESSAGE="Nothing optional happens."
	shift
	;;
esac

printf "\n${MESSAGE:=Nothing happens.}\n"

[ $# -gt 0 ] && printf "Nothing argumentative happens, either.\n"

echo

exit 0
