#!/bin/sh -e
#
# unibuild - Front-end CLI program for Unibuild
#

WHOAMI=$(basename $0)
WHEREAMI=$(dirname $0)

UNIBUILD_CANONICAL=$(readlink -e "$0")
export UNIBUILD=$(dirname "${UNIBUILD_CANONICAL}")

. "${UNIBUILD}/common"


help()
{
    echo "Usage: ${WHOAMI} COMMAND [ ARGUMENTS ]"
    echo
    echo "Commands:  (Use 'COMMAND --help' for further help.)"
    echo
    ls "${UNIBUILD_COMMANDS}" \
        | fgrep -x -v -e xyzzy \
	| pr -4 -T -t \
	| sed -e 's/^/    /g'
    echo
}


# Handle options

while echo "$1" | egrep -q -e '^--'
do
    OPTION=$1
    shift

    case "${OPTION}" in
	--define|-d)
	    set_user_macro $1
	    shift
	    ;;
    
	--help|-h|help)
	    help
	    exit 0
	    ;;

	--*)
	    die "Unknown option ${OPTION}.  Use --help for help."
	    ;;
    esac
done

if [ $# -lt 1 ]
then
    COMMAND=build
else
    COMMAND="$1"
    shift
fi


RUN="${UNIBUILD_COMMANDS}/${COMMAND}"

[ -x "${RUN}" ] \
    || die "${COMMAND}: Unknown command.  Use --help for help."

exec "${RUN}" "$@"
