#!/bin/sh -e
#
# unibuild - Front-end CLI program for Unibuild
#

WHOAMI=$(basename $0)
WHEREAMI=$(dirname $0)

UNIBUILD_CANONICAL=$(readlink -e "$0")
export UNIBUILD=$(dirname "${UNIBUILD_CANONICAL}")

. "${UNIBUILD}/common"

# Set the timestamp only if something else hasn't set it first.
[ -z "${UNIBUILD_TIMESTAMP}" ] \
    && export UNIBUILD_TIMESTAMP=$(date +%Y%m%d%H%M%S)


help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ] COMMAND [ ARGUMENTS ]"

    --define NAME=VALUE    Define Unibuild macro 'NAME' to 'VALUE'
    --release              Don't timestamp products produced

Commands:  (Use 'COMMAND --help' for further help.)"

EOF
    ls "${UNIBUILD_COMMANDS}" \
        | fgrep -x -v -e xyzzy \
	| pr -4 -T -t \
	| sed -e 's/^/    /g'
    echo
}


# Handle options

while echo "$1" | egrep -q -e '^--'
do
    OPTION=$1
    shift

    case "${OPTION}" in
	--define|-d)
	    set_user_macro "$1"
	    shift
	    ;;

	--release)
	    unset UNIBUILD_TIMESTAMP
	    ;;
    
	--help|-h|help)
	    help
	    exit 0
	    ;;

	--*)
	    die "Unknown option ${OPTION}.  Use --help for help."
	    ;;
    esac
done

if [ $# -lt 1 ]
then
    COMMAND=build
else
    COMMAND="$1"
    shift
fi


RUN="${UNIBUILD_COMMANDS}/${COMMAND}"

[ -x "${RUN}" ] \
    || die "${COMMAND}: Unknown command.  Use --help for help."

exec "${RUN}" "$@"
